# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 13:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('steam_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='steam_app.UserProfile'),
        ),
        migrations.AlterField(
            model_name='clan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='steam_app.UserProfile'),
        ),
        migrations.AlterField(
            model_name='game',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='steam_app.UserProfile'),
        ),
    ]
