# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-23 13:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('steam_app', '0002_achievement_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='appid_game',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='steam_app.Game'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='clan',
            name='name',
            field=models.CharField(default=False, max_length=50),
        ),
    ]
