# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steam_app', '0002_auto_20170421_1339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='friends',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='friends',
            field=models.TextField(blank=True, null=True),
        ),
    ]
