# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-23 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steam_app', '0003_auto_20170523_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clan',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
