# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steam_app', '0004_auto_20170420_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='appid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
