# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-23 13:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('steam_app', '0004_auto_20170523_1327'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='avatar',
            new_name='stateOrProvince',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='name',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='city',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='nickname',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='appid',
            field=models.IntegerField(default=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='steam_id',
            field=models.IntegerField(default=False, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
