# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 12:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('steam_app', '0005_auto_20170420_1207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='achievement',
            old_name='user',
            new_name='id_user',
        ),
        migrations.RenameField(
            model_name='clan',
            old_name='user',
            new_name='id_user',
        ),
        migrations.AddField(
            model_name='achievement',
            name='appid_game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='steam_app.Game'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='achievement',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='clan',
            name='id_clan',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clan',
            name='members',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='clan',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='clan',
            name='number_of_person',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='company',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='version',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='friends',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='real_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='url_profile',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
