# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 17:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('steam_app', '0008_auto_20170420_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievement',
            name='done',
        ),
        migrations.RemoveField(
            model_name='clan',
            name='id_clan',
        ),
        migrations.RemoveField(
            model_name='clan',
            name='members',
        ),
        migrations.RemoveField(
            model_name='clan',
            name='number_of_person',
        ),
        migrations.RemoveField(
            model_name='game',
            name='appid',
        ),
        migrations.RemoveField(
            model_name='game',
            name='company',
        ),
        migrations.RemoveField(
            model_name='game',
            name='version',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='country',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='friends',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='real_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='url_profile',
        ),
    ]
