# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 12:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('steam_app', '0012_auto_20170421_1158'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='achievement',
            unique_together=set([]),
        ),
        migrations.AlterUniqueTogether(
            name='game',
            unique_together=set([]),
        ),
    ]
