# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steam_app', '0013_auto_20170421_1211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='friends',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='friends',
            field=models.ManyToManyField(blank=True, null=True, related_name='_userprofile_friends_+', to='steam_app.UserProfile'),
        ),
    ]
