# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 13:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('steam_app', '0014_auto_20170421_1250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clan',
            name='id_user',
        ),
    ]
