# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steam_app', '0015_remove_clan_id_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clan',
            name='members',
            field=models.TextField(blank=True, null=True),
        ),
    ]
